[package]
name ="advent_of_code_2023"
version = "1.0.0"

[dependencies]
commons = { path = "commons"}

[[bin]]
name ="day01"
path = "./day-01/solution.rs"

# [[bin]]
# name ="day02"
# path = "./day-02/solution.rs"
#
#
#[[bin]]
#name ="day03"
#path = "./day-03/solution.rs"